import type { Metadata } from "next";
import "../../globals.css";
import Providers from "@/components/providers";
import { geistMono, geistSans } from "@/utils/fonts";

import AppSidebar from "../_components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppSidebar>{children}</AppSidebar>
        </Providers>
      </body>
    </html>
  );
}
