import type { Metadata } from "next";
import "../globals.css";
import Providers from "@/components/providers";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { rightGrotesk, spaceMono } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.variable} ${rightGrotesk.variable} antialiased`}
      >
        <Providers>
          <div className="grid min-h-[100dvh] grid-rows-[auto_1fr_auto]">
            <Header />
            <main>{children}</main>
            {/* <Footer /> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
